---
output:
  pdf_document:
    fig_caption: yes
  html_document:
    fig_caption: yes
---

# Exercise 6 - Comparison to `INLA` and inclusion of covariate information

## a) Implementation in `R-INLA`

```{r}
library(INLA)
attach(Oral)

g <- system.file("demodata/germany.graph", package="INLA")
data <- tibble(
  region_structured = seq(1, problem$n),
  region_random = seq(1, problem$n),
  Y = Oral$Y,
  E = Oral$E
)

kappa_v_hyper <- list(
  prec = list(prior = "loggamma", param = c(1, 0.01))
)
kappa_u_hyper <- list(
  prec = list(prior = "loggamma", param = c(1, 0.01))
)


formula <- Y ~
  -1 +
  f(region_structured, model="besag", graph = g, hyper = kappa_u_hyper, constr = FALSE) +
  f(region_random, model = "iid", hyper = kappa_v_hyper)

inla_result <- inla(
  formula = formula,
  family = "poisson",
  data = data,
  E = E,
  verbose = FALSE,
  control.compute = list(dic = TRUE)
)
inla_result <- inla.hyperpar(inla_result)

uv_marginals <- inla_result$marginals.random
inla_u <- uv_marginals$region_structured
inla_v <- uv_marginals$region_random

marginals <- inla_result$marginals.hyperpar
inla_kappa_u <- marginals$`Precision for region_structured`
inla_kappa_v <- marginals$`Precision for region_random`

inla_kappa_u_smoothed <- as_tibble(inla_kappa_u)
inla_kappa_v_smoothed <- as_tibble(inla_kappa_v)
```

```{r, fig.width = 8.3, fig.height = 9, fig.fullwidth=TRUE, fig.cap = "\\label{fig:marginals}Plots comparing the posterior marginals obtained by INLA, drawn in red, to histograms of the MCMC-samples, drawn in grey. The y-axis is normalized such that both integrate to 1. First column shows u-components, second column the v-components, while the third shows $\kappa_u$ and $\kappa_v$."}
plot_marginal <- function(param, marginal, binwidth) {
  #' Plot histogram of MCMC samples on top of posterior marginals
  #' obtained from INLA.
  param_samples <- usable_samples %>% pull(param)
  min_x <- min(param_samples)
  max_x <- max(param_samples)
  
  plot <- usable_samples %>%
    ggplot() +
    geom_histogram(
      aes_string(x = param, y = "..density.."),
      binwidth = binwidth
    ) +
    geom_line(
      data = data.frame(marginal),
      aes(x = x, y = y),
      color = "red"
    ) +
    xlim(min_x, max_x) +
    labs(title = param, x = "", y = "")
  return(plot)
}

plots <- list(
  # u-components
  plot_marginal("u_80", inla_u[[80]], 0.01),
  plot_marginal("u_360", inla_u[[360]], 0.01),
  plot_marginal("u_500", inla_u[[500]], 0.01),
  # v-components
  plot_marginal("v_80", inla_v[[80]], 0.01),
  plot_marginal("v_360", inla_v[[360]], 0.01),
  plot_marginal("v_500", inla_v[[500]], 0.01),
  # kappas
  plot_marginal("kappa_u", inla_kappa_u, 0.4),
  plot_marginal("kappa_v", inla_kappa_v, 5)
)

library(gridExtra)
layout <- rbind(
  c(1, 4, 7), c(1, 4, 7), c(2, 5, 7),
  c(2, 5, 8), c(3, 6, 8), c(3, 6, 8)
)
grid.arrange(grobs = plots, layout_matrix = layout, left = "density", bottom = "parameter value")
```

A comparison between MCMC and INLA, specifically the spatially structured effect $\exp(\hat{u}_i)$. The MCMC result is portrayed on the left hand side, while INLA's result is portrayed on the right hand side."}

```{r, fig.cap = "\\label{fig:inla_germany}"}
uv_summaries <- inla_result$summary.random
u_summary <- uv_summaries$region_structured
inla_exp_u_median <- u_summary$`0.5quant` %>% exp() %>% as_vector()
par(mfcol=c(1, 2))
germany.plot(
  exp_u_median,
  col=col,
  legend=TRUE,
  main = bquote("MCMC"),
  cex.mai = 1.5
)
germany.plot(
  inla_exp_u_median,
  col=col,
  legend=TRUE,
  main = bquote("INLA"),
  cex.mai = 1.5
)
```

## b) Smoking as new covariate

```{r}
smoking = read.table("data/smoking.dat")$V1
data <- add_column(data, smoking) 

linear_smoking_formula <- Y ~
  -1 +
  f(region_structured, model="besag", graph = g, hyper = kappa_u_hyper, constr = FALSE) +
  f(region_random, model = "iid", hyper = kappa_v_hyper) +
  smoking

linear_inla_result <- inla(
  formula = linear_smoking_formula,
  family = "poisson",
  data = data,
  E = E,
  verbose = FALSE,
  control.compute = list(dic = TRUE)
)

nonlinear_smoking_formula <- Y ~
  -1 +
  f(region_structured, model="besag", graph = g, hyper = kappa_u_hyper, constr = FALSE) +
  f(region_random, model = "iid", hyper = kappa_v_hyper) +
  f(smoking, model = "rw2")
nonlinear_inla_result <- inla(
  formula = nonlinear_smoking_formula,
  family = "poisson",
  data = data,
  E = E,
  verbose = FALSE,
  control.compute = list(dic = TRUE)
)
```
