---
output:
  pdf_document: default
  html_document: default
  word_document: default
---
# Exercise 1 - Derivations

\providecommand{\kappau}{\kappa_u}
\providecommand{\kappav}{\kappa_v}
\providecommand{\uvec}{\boldsymbol{u}}
\providecommand{\Rmat}{\boldsymbol{R}}
\providecommand{\yvec}{\boldsymbol{y}}
\providecommand{\Evec}{\boldsymbol{E}}
\providecommand{\etavec}{\boldsymbol{\eta}}

## a) Derivation of the posterior distribution

In order to find the posterior distribution $p(\etavec, \uvec, \kappa_u, \kappa_v \mid \yvec)$ we start off by noting that 

$$
p(\etavec, \uvec, \kappa_u, \kappa_v \mid \yvec) \propto p(\etavec, \uvec, \kappa_u, \kappa_v, \yvec).
$$
This can be rewritten by using the definition of conditional probability, resulting in

$$
p(\etavec, \uvec, \kappa_u, \kappa_v, \yvec) \propto p(\yvec \mid \etavec, \uvec, \kappa_u, \kappa_v)p(\etavec, \uvec, \kappa_u, \kappa_v).
$$
We proceed by noting that

\begin{align*}
p(\etavec, \uvec, \kappa_u, \kappa_v) &= p(\etavec \mid \uvec, \kappa_u, \kappa_v)p(\uvec, \kappa_u, \kappa_v) \\
&= p(\etavec \mid \uvec, \kappa_u, \kappa_v)p(\uvec \mid \kappa_u, \kappa_v)p(\kappa_u, \kappa_v).
\end{align*}

Since $\yvec$ only depends on $\etavec$, $\etavec$ is indepedent of $\kappa_u$, $\uvec$ is independent of $\kappa_v$, and $\kappa_u$ and $\kappa_v$ are independent we obtain that

\begin{align*}
p(\etavec, \uvec, \kappa_u, \kappa_v \mid \yvec) &\propto p(\yvec \mid \etavec, \uvec, \kappa_u, \kappa_v)p(\etavec \mid \uvec, \kappa_u, \kappa_v)p(\uvec \mid \kappa_u, \kappa_v)p(\kappa_u, \kappa_v) \\
&= p(\yvec \mid \etavec)p(\etavec \mid \uvec, \kappa_v)p(\uvec \mid \kappa_u)p(\kappa_u)p(\kappa_v).
\end{align*}

Inserting the expressions for the probability distributions, combined with 

\begin{align*}
p(\yvec\mid\etavec) &= \prod_{i=1}^n\frac{(E_i\exp(\eta_i))^{y_i}}{y_i!}\exp({-E_i\exp(\eta_i)}) \\
&\propto \exp(\sum_{i=1}^ny_i\log(E_i) + y_i\eta_i - E_i\exp(\eta_i)) \\ 
&\propto \exp(\sum_{i=1}^ny_i\eta_i - E_i\exp(\eta_i))
\end{align*}

and 


\begin{align*}
p(\kappa_u)p(\kappa_v) &= \frac{\beta_v^{\alpha_v}}{\Gamma(\alpha_v)}\frac{\beta_u^{\alpha_u}}{\Gamma(\alpha_u)}\kappa_v^{\alpha_v - 1}\kappa_u^{\alpha_u - 1}\exp(-\beta_v\kappa_v - \beta_u\kappa_u)\\ &\propto \kappa_v^{\alpha_v - 1}\kappa_u^{\alpha_u - 1}\exp(-\beta_v\kappa_v - \beta_u\kappa_u)
\end{align*}

we get that


\begin{align*}
p(\etavec, \uvec, \kappa_u, \kappa_v \mid \yvec) &\propto p(\yvec\mid\etavec)p(\etavec\mid\uvec,\kappa_v)p(\uvec\mid\kappa_u)p(\kappa_u)p(\kappa_v) \\
&\propto \kappa_v^{\alpha_v - 1 + \frac{n}{2}}\kappa_u^{\alpha_u - 1 + \frac{n-1}{2}}\times\\&\exp(-\beta_v\kappa_v - \beta_u\kappa_u - \frac{\kappa_u}{2}\uvec^T\Rmat\uvec - \frac{\kappa_v}{2}(\etavec - \uvec)^T(\etavec - \uvec) + \sum_{i=1}^n(y_i\eta_i - E_i\exp(\eta_i))).
\end{align*}


## b) Simplification of the posterior

The second - order Taylor expansion of $f(\eta_i) = y_i\eta_i - E_i\exp(\eta_i)$ around $z_i$ is given by

$$
\tilde{f}(\eta_i) = f(z_i) + f'(z_i)(\eta_i - z_i) + \frac{f''(z_i)}{2}(\eta_i - z_i)^2
$$
We note that $f'(\eta_i) = y_i - E_i\exp(\eta_i)$ and $f''(\eta_i) = -E_i\exp(\eta_i)$, leading to 

\begin{align*}
\tilde{f}(\eta_i) &= y_iz_i - E_i\exp(z_i) + (y_i - E_i\exp(z_i))(\eta_i - z_i) - \frac{E_i}{2}(\eta^2 + 2\eta_iz_i + z_i^2) \\ &= E_i\exp(z_i)\left[z_i - \frac{z_i^2}{2} - 1\right] + \eta_i(y_i - E_i\exp(z_i)\left(z_i -1\right)) - \eta_i^2\frac{E_i\exp(z_i)}{2} \\
&= a_i + \eta_ib_i - \eta_i^2\frac{c_i}{2},
\end{align*}

with $a_i = E_i\exp(z_i)\left[z_i - \frac{z_i^2}{2} - 1\right]$, $b_i = y_i - E_i\exp(z_i)\left(z_i -1\right)$ and $c_i = E_i\exp(z_i)$.

## c) Derivation of full conditionals

The full conditional density $p(\kappa_u \mid \etavec, \yvec, \uvec, \kappa_v)$ is obtained by noting that $p(\kappa_u \mid \etavec, \yvec, \uvec, \kappa_v) \propto p(\kappa_u, \etavec, \yvec, \uvec, \kappa_v)$. Proceeding from here, we obtain that

\begin{align*}
p(\kappa_u \mid \etavec, \yvec, \uvec, \kappa_v) &\propto p(\kappa_u, \etavec, \yvec, \uvec, \kappa_v) \\
&= p(\uvec \mid \etavec, \yvec, \kappa_u, \kappa_v)p(\etavec, \yvec, \kappa_u, \kappa_v) \\
&\propto p(\uvec \mid \etavec, \yvec, \kappa_u, \kappa_v)p(\kappa_u \mid \etavec, \yvec, \kappa_v) \\
&= p(\uvec \mid \kappa_u)p(\kappa_u) \\
&\propto \kappa_u^{\alpha_u + \frac{n-1}{2} - 1}\exp\left(-\kappa_u\left[\frac{1}{2}\uvec^T\Rmat\uvec + \beta_u\right]\right)
\end{align*}

The full conditional density $p(\kappa_v \mid \etavec, \yvec, \uvec, \kappa_u)$ satisfies


\begin{align*}
p(\kappa_v \mid \etavec, \yvec, \uvec, \kappa_u) &\propto p(\etavec, \yvec, \uvec, \kappa_u \mid \kappa_v)p(\kappa_v) \\
&= p(\etavec \mid \yvec, \uvec, \kappa_u, \kappa_v)p(\uvec, \yvec, \kappa_u \mid \kappa_v)p(\kappa_v).
\end{align*}



Using that 

$$
p(\uvec, \yvec, \kappa_u \mid \kappa_v) \propto \frac{p(\kappa_v \mid \uvec, \yvec, \kappa_u)}{p(\kappa_v)}
$$
we obtain

\begin{align*}
p(\kappa_v \mid \etavec, \yvec, \uvec, \kappa_u) &\propto p(\etavec \mid \yvec, \uvec, \kappa_u, \kappa_v)p(\kappa_v \mid \uvec, \yvec, \kappa_u) \\
&= p(\etavec \mid \uvec, \kappa_v)p(\kappa_v) \\
&\propto \kappa_v^{\alpha_v + \frac{n}{2} - 1}\exp\left(-\kappa_v\left[\frac{1}{2}(\etavec - \uvec)^T(\etavec - \uvec) + \beta_v\right]\right).
\end{align*}
The full posterior $p(\uvec \mid \etavec, \yvec, \kappa_u, \kappa_v)$ is given by 

\begin{align*}
p(\uvec \mid \etavec, \yvec, \kappa_u, \kappa_v) &\propto p(\uvec, \etavec, \yvec, \kappa_u, \kappa_v) \\
&= p(\etavec \mid \uvec, \yvec, \kappa_u, \kappa_v)p(\uvec, \yvec, \kappa_u, \kappa_v) \\
&\propto p(\etavec \mid \uvec, \yvec, \kappa_u, \kappa_v)p(\uvec \mid \yvec, \kappa_u, \kappa_v) \\
&= p(\etavec \mid \uvec, \kappa_v)p(\uvec \mid \kappa_u) \\
&\propto \kappa_u^{\frac{n-1}{2}}\kappa_v^{\frac{n}{2}}\exp\left(-\frac{1}{2}\left[\kappa_u\uvec^T\Rmat\uvec + (\etavec - \uvec)^T\kappa_v\boldsymbol{I}(\etavec - \uvec)\right]\right) \\
&\propto \exp\left(-\frac{1}{2}\uvec^T\left(\kappa_u\Rmat + \kappa_v\boldsymbol{I}\right)\uvec - \kappa_v\etavec^T\uvec\right).
\end{align*}

The full posterior $p(\etavec \mid \uvec, \yvec, \kappa_u, \kappa_v)$ is given by 

\begin{align*}
p(\etavec \mid \uvec, \yvec, \kappa_u, \kappa_v) &\propto p(\etavec, \uvec, \yvec, \kappa_u, \kappa_v) \\
&= p(\yvec \mid \etavec, \uvec, \kappa_u, \kappa_v)p(\etavec, \uvec, \kappa_u, \kappa_v) \\
&\propto p(\yvec \mid \etavec, \uvec, \kappa_u, \kappa_v)p(\etavec \mid \uvec, \kappa_u, \kappa_v) \\
&= p(\yvec \mid \etavec)p(\etavec \mid \uvec, \kappa_v) \\
&\propto \exp\left(\sum_{i=1}^{n}(y_i\eta_i - E_i\exp(\eta_i)) - \frac{\kappa_v}{2}(\etavec - \uvec)^T\boldsymbol{I}(\etavec - \uvec) \right) \\
&\propto \exp\left(\yvec^T\etavec - \exp(\etavec)^T\boldsymbol{E} + \etavec^T(\kappa_v\uvec) - \frac{1}{2}\etavec^T(\kappa_v\boldsymbol{I})\etavec\right).
\end{align*}

In preceding calculation we've used that 
$$
\frac{\kappa_v}{2}(\etavec - \uvec)^T\boldsymbol{I}(\etavec - \uvec) = 
\sum_{i=1}^n\frac{\kappa_v}{2}(\eta_i - u_i)^2 = \frac{\kappa_v}{2}\sum_{i=1}^n\eta_i^2 - 2\eta_iu_i + u_i^2 = \frac{1}{2}\etavec^T(\kappa_v\boldsymbol{I})\etavec - \etavec^T(\kappa_v\uvec) + \frac{\kappa_v}{2}\uvec^T\uvec
$$
 
We recognize $\sum_{i=1}^{n}(y_i\eta_i - E_i\exp(\eta_i))$ as $\sum_{i=1}^nf(\eta_i)$. By substituting $f(\eta_i)$ for it's approximation $\tilde{f}(\eta_i)$ we get $\sum_{i=1}^n\tilde{f}(\eta_i) = \sum_{i=1}^na_i + \etavec^T\boldsymbol{b} - \frac{1}{2}\etavec^T\textrm{diag}(\boldsymbol{c})\etavec$, where $\boldsymbol{b} = \begin{bmatrix}b_1, \ldots, b_n\end{bmatrix}^T$ and $\boldsymbol{c} = \begin{bmatrix}c_1, \ldots, c_n\end{bmatrix}^T$. 

This enables us to find the following approximation of $p(\etavec \mid \uvec, \yvec, \kappa_u, \kappa_v)$.

\begin{align*}
q(\etavec \mid z, \uvec, \yvec, \kappa_u, \kappa_v) &\propto \exp\left(\etavec^T\boldsymbol{b} - \frac{1}{2}{\etavec}^T\textrm{diag}(\boldsymbol{c})\etavec + \etavec^T(\kappa_v\uvec) - \frac{1}{2}\etavec^T(\kappa_v\boldsymbol{I})\etavec) \right) \\
&\propto \exp\left(-\frac{1}{2}\etavec^T(\textrm{diag}(\boldsymbol{c}) + \kappa_v\boldsymbol{I}))\etavec + \etavec^T(\boldsymbol{b} + \kappa_v\uvec)\right) \\
\end{align*}



