## Problem C: The Dirichlet distribution: simulating using known relations

Define the $K$ dimensional stochastic vector $\vec{x} := (x_1, ..., x_K)$ where $x_k \in [0, 1]$ and $\sum_{x = 1}^{K} x_k = 1$.
Since $x_K$ is determined by $(x_1, ..., x_{K - 1})$, define $\tilde{x} := (x_1, ..., x_{K - 1})$.
Also, define the the parameter vector $\vec{\alpha} = (\alpha_1, ..., \alpha_K).

The vector $\vec{x}$ is said to have a Dirichlet distribution with parameter $\vec{\alpha}$ when the probability density for $\tilde{x}$ is given by

$$
f(\tilde{x}; \vec{\alpha}) = \frac{\Gamma(\sum_{k = 1}^{K} \alpha_k)}{\prod_{k = 1}^{K}{\alpha_k}} \cdot \bigg( \prod_{k = 1}^{K - 1}{x_k^{\alpha_k - 1}} \bigg) \cdot \bigg(1 - \sum_{k = 1}^{K - 1} x_k \bigg)^{\alpha_K - 1}
$$

for $x_1, ..., x_{K - 1} > 0$ and $\sum_{k = 1}^{K - 1} x_k < 1$.

### 1. Theory

Define a new $K$-dimensional stochastic vector $\vec{z} := (z_1, ... z_K)$ where $z_k \sim \text{gamma}(\alpha_k, 1)$, where $z_k$ are independently distributed. We will now show that the transformation

$$
x_k = \frac{z_k}{\sum_{k=1}^{K} z_k}
$$
results in $\vec{x}$ being Dirichlet distributed with parameter vector $\vec{\alpha}$.

Since the $z_k$'s are identically and idependently distributed, the joint distribution can be found by

$$
\begin{align}
  f_{z_k}(z_k; \alpha_k) &= \frac{z_k^{\alpha_k - 1} e^{-z_k}}{\Gamma(\alpha_k)} \\
  \implies f_z(\vec{z}; \vec{\alpha}) &= \prod_{k = 1}^{K} f_{z_k}(z_k; \alpha_k)
  = \prod_{k = 1}^{K} \left( \frac{z_k^{\alpha_k - 1}}{\Gamma(\alpha_k)} \right) e^{-v} \\
  v :&= \sum_{k = 1}^{K} z_k.
\end{align}
$$

Now, perform a transformation, $h$, of the variable $\vec{z}$ to $(x_1, ..., x_{K - 1}, v)$, with $v$ as defined above. This yields

$$
\begin{align}
  x_k &= \frac{z_k}{v} \\
  \implies z_k &=
  \begin{cases}
    h_k(x_k, v) = v \cdot x_k &, k \in \left{1,~...,~K - 1\right} \\
    h_K(\tilde{x}, v) = v \cdot (1 - \sum_{k = 1}^{K - 1} x_k), &, k = K
  \end{cases} \\
  \implies \vec{z} &= v \vec{x}
  = \left(v \cdot x_1,~...,~v \cdot x_{K - 1}, v \cdot \left[1 - \sum_{k = 1}^{K - 1} x_k\right]\right).
\end{align}
$$

The change-of-variables formula gives the new joint distribution as

$$
f_x(\tilde{x}, v; \vec{\alpha}) = f_z(\vec{z}; \vec{\alpha}) \cdot |J|,
$$

where $|J|$ is the determinant of the Jacobian. It is defined by

$$
J_{j, k} = \frac{\text{d}z_k}{\text{d}x_j},
$$

for row $j$ and column $k$.

(Derive form of J)

This Jacobian matrix can be reduced to upper triangular form by $K - 1$ row additions
without changing its determinant.
The determinant of an upper triangular matrix is the product of its diagonal entries, which results in

$$
\det
\begin{bmatrix}
  v  & 0  & \dots  & 0  & x_1 \\
  0  & v  & \dots  & 0  & x_2 \\
  \vdots  & \vdots  & \ddots  & \vdots  & \vdots \\
  0  & 0  & \dots  & v  & x_{K - 1} \\
  -v  & -v  & \dots  & -v  & 1 - \sum_{k = 1}^{K - 1} x_k
\end{bmatrix}
= 
\det
\begin{bmatrix}
  v  & 0  & \dots  & 0  & x_1 \\
  0  & v  & \dots  & 0  & x_2 \\
  \vdots  & \vdots  & \ddots  & \vdots  & \vdots \\
  0  & 0  & \dots  & v  & x_{K - 1} \\
  0  & 0  & \dots  & 0  & 1
\end{bmatrix}
=
v^{k - 1}
$$

### 2. Implementation

```{r}
rdirichlet <- function(n, alpha) {
  gammaSamples <- random_sample_from_f(n = n, alpha = alpha, beta = 1)
  return(1)
}
```
