---
output:
  pdf_document: default
  html_document: default
---
```{r, include=FALSE}
knitr::set_parent("base.Rmd")

library(tidyverse)
library(broom)
library(tibble)
```

## Problem B

### B1

The hypothesis is rejected at significance $\alpha = 0.95$, seeing as the p-value is less than 0.05.

```{r}
bilirubin <- here::here("reports", "report_3", "data", "bilirubin.txt") %>%
  read.table(header=T) %>%
  as_tibble()

bilirubin %>%
  mutate(log_meas = log(meas)) %>%
  ggplot(aes(x=pers, y=log_meas)) +
  geom_boxplot()

linear_model <- lm(log(meas)~pers, data=bilirubin)

summary(linear_model)

Fval <- linear_model %>%
  glance() %>%
  pull(statistic)
```

### B2

```{r}
permTest <- function(df){
  perm_df <- tibble(meas = df %>%
                      pull(meas) %>% 
                      sample(),
                    pers = df %>% 
                      pull(pers)
  )
  lm(log(meas)~pers, data=perm_df) %>% 
    glance() %>% 
    pull(statistic)
}

permTest_df <- tibble(
  run = seq(1, 999),
  F_stat = 999 %>%
    rerun(permTest(bilirubin))
  ) %>%
  unnest()
```

### B3

```{r}

perc_95 <- permTest_df %>%
  pull(F_stat) %>% 
  quantile(probs = c(0.95))

permTest_df %>%
  ggplot(aes(x=F_stat)) +
  geom_histogram(bins=50) +
  geom_vline(aes(xintercept=perc_95), color="red") +
  geom_vline(aes(xintercept=Fval), color="green")

p_value <- permTest_df %>%
  pull(F_stat) %>%
  map_lgl(~.x >= Fval) %>%
  mean()

p_value
```




